version: '2'
services:

  edge-service:
    build: edge-service
    container_name: edge-service
    mem_limit: 512M
    network_mode: "host"
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev

  fund-service:
    build: fund-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/fund-service-latest.jar"
    mem_limit: 512M
    network_mode: "host"
    ports:
      - 10010:10010
    environment:
      SPRING_PROFILES_ACTIVE: dev

  inventory-service:
    build: inventory-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/inventory-service-latest.jar"
    mem_limit: 512M
    network_mode: "host"
    ports:
      - 10011:10011
    environment:
      SPRING_PROFILES_ACTIVE: dev
 
  invest-service:
    build: invest-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/invest-service-latest.jar"
    mem_limit: 512M
    network_mode: "host"
    ports:
      - 10012:10012
    environment:
      SPRING_PROFILES_ACTIVE: dev

  trade-service:
    build: trade-service
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/trade-service-latest.jar"
    mem_limit: 512M
    network_mode: "host"
    ports:
      - 10013:10013
    environment:
      SPRING_PROFILES_ACTIVE: dev

  web-gateway:
    build: web-gateway
    command: /bin/bash -c "wait-for-it -t 0 localhost:3306 && /app/start /app/web-gateway-latest.jar"
    mem_limit: 512M
    network_mode: "host"
    ports:
      - 10014:10014
    environment:
      SPRING_PROFILES_ACTIVE: dev
