server:
  port: 10010

spring:
  profiles: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/investmentdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---

server:
  port: 10010

spring:
  profiles: docker
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://mariadb:3306/investmentdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect