server:
  port: 10011

kafka:
  stream:
    appid: fund-service-kafka-stream
  broker:
    host: kafka:9092
  zookeeper:
    host: kafka:2181

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:inventorydb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

management:
  security:
    enabled: false

---

server:
  port: 10011

spring:
  profiles: docker
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://mariadb:3306/inventorydb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
