server:
  port: 10011

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

management:
  security:
    enabled: false

kafka:
  stream:
    appid: inventory-service-kafka-stream
  broker:
    host: kafka:9092
  zookeeper:
    host: kafka:2181

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mariadb:3307/inventorydb

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoery-service:10100/eureka/
